### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Aboshxm2** [TitaniumLB6571/TitanCommandSpy#3]
[Tue_Jan_3-18.31.52-+03_2023.log](https://github.com/TitaniumLB6571/TitanCommandSpy/files/10341419/Tue_Jan_3-18.31.52-%2B03_2023.log)
Server crashing when trying to send a message to not connected player.

Steps to reproduce the issue:
1. Send /commandspy
2. Leave the server
3. Have someone else enter the server
4. Let him send any command
and the server is crashing

**Comment by TitaniumLB6571** [comment]
Fixed, thanks. Even if its been a few months lol
